export const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
export type PolymerListItem={id:string;name:string;canonical_name:string;polymer_class:string|null;architecture:string;structure_count:number;property_record_count:number;created_at:string;updated_at:string};
export type Page<T>={items:T[];total:number;limit:number;offset:number};
export type Polymer=PolymerListItem&{description:string|null;number_average_molecular_weight:number|null;weight_average_molecular_weight:number|null;dispersity:number|null;degree_of_polymerization:number|null;structures:Structure[];property_records:PropertyRecord[]};
export type Structure={id:string;representation_type:string;representation:string;is_canonical:boolean;source:string|null};
export type PropertyDefinition={id:string;key:string;name:string;symbol:string|null;canonical_unit:string;category:string|null};
export type Provenance={id:string;source_type:string;title:string|null;authors:string|null;year:number|null;doi:string|null;url:string|null;dataset_name:string|null;notes:string|null};
export type PropertyRecord={id:string;value:number;unit:string;uncertainty:number|null;method:string|null;provenance_type:string;conditions:Record<string,unknown>|null;property:PropertyDefinition;provenance:Provenance|null};
export class ApiError extends Error { constructor(public status:number,message:string){super(message)} }
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${apiBaseUrl}${path}`,{...init,headers:{"Content-Type":"application/json",...init?.headers}});if(!response.ok){let detail="Request failed";try{const body=await response.json();detail=typeof body.detail==="string"?body.detail:JSON.stringify(body.detail)}catch{}throw new ApiError(response.status,detail)}return response.json() as Promise<T>}
export const api={listPolymers:(params:URLSearchParams)=>request<Page<PolymerListItem>>(`/api/v1/polymers?${params}`),getPolymer:(id:string)=>request<Polymer>(`/api/v1/polymers/${id}`),createPolymer:(body:unknown)=>request<Polymer>("/api/v1/polymers",{method:"POST",body:JSON.stringify(body)}),listDefinitions:()=>request<Page<PropertyDefinition>>("/api/v1/property-definitions?limit=100"),createProvenance:(body:unknown)=>request<Provenance>("/api/v1/provenance",{method:"POST",body:JSON.stringify(body)}),createRecord:(id:string,body:unknown)=>request<PropertyRecord>(`/api/v1/polymers/${id}/properties`,{method:"POST",body:JSON.stringify(body)})};
