export const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
export type ValidationStatus="not_validated"|"valid"|"partially_valid"|"invalid"|"unsupported";
export type FingerprintConfig={algorithm:"Morgan";radius:2;n_bits:2048;attachment_handling:"wildcards_retained"};
export type ChemistryMetadata={validation_status:ValidationStatus;validation_message:string|null;normalized_representation:string|null;connection_point_count:number|null;normalization_version:string|null;rdkit_version:string|null;validated_at:string|null;derived_properties:Record<string,number>|null};
export type ChemistryValidation={status:ValidationStatus;validation_message:string|null;warnings:string[];normalized_representation:string|null;connection_point_count:number|null;derived_properties:Record<string,number>|null;rdkit_version:string|null;normalization_version:string|null;validated_at:string|null;fingerprint_config:FingerprintConfig};
export type SimilarityResult={polymer_id:string;polymer_name:string;structure_id:string;raw_representation:string;normalized_representation:string;similarity:number;fingerprint_config:FingerprintConfig};
export type SimilaritySearchResponse={items:SimilarityResult[];fingerprint_config:FingerprintConfig};
export type PolymerListItem={id:string;name:string;canonical_name:string;polymer_class:string|null;architecture:string;structure_count:number;property_record_count:number;created_at:string;updated_at:string};
export type Page<T>={items:T[];total:number;limit:number;offset:number};
export type Polymer=PolymerListItem&{description:string|null;number_average_molecular_weight:number|null;weight_average_molecular_weight:number|null;dispersity:number|null;degree_of_polymerization:number|null;structures:Structure[];property_records:PropertyRecord[]};
export type Structure={id:string;representation_type:string;representation:string;is_canonical:boolean;source:string|null}&ChemistryMetadata;
export type PropertyDefinition={id:string;key:string;name:string;symbol:string|null;canonical_unit:string;category:string|null};
export type Provenance={id:string;source_type:string;title:string|null;authors:string|null;year:number|null;doi:string|null;url:string|null;dataset_name:string|null;notes:string|null};
export type PropertyRecord={id:string;value:number;unit:string;uncertainty:number|null;method:string|null;provenance_type:string;conditions:Record<string,unknown>|null;property:PropertyDefinition;provenance:Provenance|null};
export class ApiError extends Error { constructor(public status:number,message:string){super(message)} }
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${apiBaseUrl}${path}`,{...init,headers:{"Content-Type":"application/json",...init?.headers}});if(!response.ok){let detail="Request failed";try{const body=await response.json();detail=typeof body.detail==="string"?body.detail:JSON.stringify(body.detail)}catch{}throw new ApiError(response.status,detail)}return response.json() as Promise<T>}
export const api={listPolymers:(params:URLSearchParams)=>request<Page<PolymerListItem>>(`/api/v1/polymers?${params}`),getPolymer:(id:string)=>request<Polymer>(`/api/v1/polymers/${id}`),createPolymer:(body:unknown)=>request<Polymer>("/api/v1/polymers",{method:"POST",body:JSON.stringify(body)}),validateStructure:(body:{representation_type:string;representation:string})=>request<ChemistryValidation>("/api/v1/chemistry/validate",{method:"POST",body:JSON.stringify(body)}),similaritySearch:(body:{representation_type:string;representation:string;minimum_similarity:number;limit:number})=>request<SimilaritySearchResponse>("/api/v1/chemistry/similarity-search",{method:"POST",body:JSON.stringify(body)}),listDefinitions:()=>request<Page<PropertyDefinition>>("/api/v1/property-definitions?limit=100"),createProvenance:(body:unknown)=>request<Provenance>("/api/v1/provenance",{method:"POST",body:JSON.stringify(body)}),createRecord:(id:string,body:unknown)=>request<PropertyRecord>(`/api/v1/polymers/${id}/properties`,{method:"POST",body:JSON.stringify(body)})};
